#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var wercker = require('./lib/wercker.js').Wercker;

program
  .version('0.0.1')


program
    .command('create [env]')
    .description('create a wercker project')
    .action(function() {
        console.log('creating Wercker project with ' + env + ' environment');
        wercker.create(env);
    });


program.on('--help', function() {
    console.log(' Examples:');
    console.log('');
});

program.parse(process.argv);

