#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var Wercker = require('./lib/wercker.js').Wercker;
var wercker = new Wercker();


program
  .version('0.0.1')


program
    .command('create [env]')
    .description('create a wercker project')
    .action(function(env) {
        console.log('Creating Wercker project with ' + env + ' environment');
        wercker.create(env);
    });

program
    .command('template')
    .description('installs the template for this project type')
    .action(function(env) {
        console.log('Retrieving the template files');
        wercker.template();
    });


program.on('--help', function() {
    console.log(' Examples:');
    console.log('');
});

program.parse(process.argv);

