#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');

program
  .version('0.0.1')


program
    .command('init')
    .description('create a wercker project')
    .action(function() {
        console.log('-- create wercker project not implemented yet');
    });


program.on('--help', function() {
    console.log(' Examples:');
    console.log('');
});

program.parse(process.argv);

